# Generated by Django 5.1.1 on 2024-09-14 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_blog_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
